FROM registry.access.redhat.com/ubi9/python-311:latest

USER root
RUN pip install --no-cache-dir huggingface-hub hf_transfer

COPY download_model.py /app/download_model.py
WORKDIR /app

ENTRYPOINT ["python", "download_model.py"]